typeExtension: typeExtension.js
customRules: customRules.js
codeframes: on
rules:
  overlaysMerger:
    executionOrder: early
  mergeChecker:
    executionOrder: late

  bundler: off
  debug-info: off

  parameterPartial: warning
  parameterWithAllOf: warning

  oas3-schema/parameter: off
  oas3-schema/external-docs:
    url: off

  api-servers: off

  path-param-exists: on
  operation-2xx-response: on
  unique-parameter-names: on
  no-unused-schemas: on
  operation-operationId-unique: on
  path-declarations-must-exist: on
  
  license-url: on
  no-extra-fields: on
  operation-description: off
  operation-operationId: off
  operation-tags: off
  provide-contact: on
  servers-no-trailing-slash: on
